include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    sort_constructors_first: false
    public_member_api_docs: false
    sort_pub_dependencies: false
    avoid_positional_boolean_parameters: false
    avoid_dynamic_calls: false
    one_member_abstracts: false
    library_private_types_in_public_api: false
    unnecessary_lambdas: false
    flutter_style_todos: false

analyzer:
  exclude:
    - lib/inject.config.dart
    - '**.g.dart'

  language:
    strict-casts: false
    strict-raw-types: false

  errors:
    inference_failure_on_untyped_parameter: ignore
